### PR TITLE
bad relations

### PR DESCRIPTION
**Pull request by morr**

### CODE REVIEW

**Comment by Wopian** [comment]
IMO this shouldn't be a bad relationship:

```
+A28149 #Nihon Animator Mihonichi
+A3785  #Evangelion: 3.0 You Can (Not) Redo
+A80    #Mobile Suit Gundam
```

http://animatorexpo.com/evangelionanotherimpact/
http://animatorexpo.com/gensatsu_gundam/

**Comment by morr** [comment]
@Wopian do you mean that instead of
```
A28149 #Nihon Animator Mihonichi
A3785  #Evangelion: 3.0 You Can (Not) Redo
A80    #Mobile Suit Gundam
```
it should be
```
A3785  #Evangelion: 3.0 You Can (Not) Redo
A80    #Mobile Suit Gundam
```
?

Because Gundam and Evangelion are definitely not the same franchise.

**Comment by Wopian** [comment]
>it should be

Pretty much. Because while Gundam and Eva themselves are completely different, the Nihon project has shorts from both franchises and should be related to both - which the original commit would've completely forbidden.

**Comment by rr-** [comment]
Waiting for @tehoko reaction

**Comment by tehoko** [comment]
The problem is, `Nihon` is a bridge between the two franchises. As far as I know, when our engine spots a common title in two separate franchises, it immediately groups them together.

So if you want to keep `Gundam` and `Evangelion` separate, you have to cut the bridge in two places: `Gundam-Nihon` and `Nihon-Evangelion`. Although you could keep one of those bridges, cutting both ensures there's no unnecessary relations to crossovers like `Nihon`. This is why the "bad group" has three elements, and it has to stay this way.

**Comment by morr** [comment]
@tehoko added new commit with `Gundam-Nihon` and `Nihon-Evangelion` cut

**Comment by morr** [comment]
Btw maybe you would find [my script](http://codepen.io/morr/pen/gbQxzR) useful to you. It shows a d3 graph with all franchise relations for specified anime (it takes into account all bans from [here](https://github.com/morr/malgraph4/blob/master/data/banned-franchise-coupling.lst)).

**Comment by rr-** [comment]
How come shikimori.org's API uses the same anime IDs as MAL?

**Pull request merged**
